[package]
name = "task-crab"
description = "A simple CLI task handler application"
authors = ["Gergő Csókás <gergo.csokas@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["default"] }
directories = "5.0.1"
